# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaskChat
  pod 'Firebase/Core'
  pod 'FirebaseMessaging'

  target 'TaskChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TaskChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaskChat-tvOS

  target 'TaskChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
